### ISSUE TITLE
New PSF Path

### ISSUE THREAD

**Issue by orifox** [jpierel14/space_phot#5]
I think Jay may have changed his PSF path. I find I need to change the following in PSFPhot.py

Line 735: PSFSTD -> STDPSF
Line 743: url -> 'https://www.stsci.edu/~jayander/HST1PASS/LIB/PSFs/STDPSFs/{}/{}'

I'm not entirely sure. The old ones may still be there. But I checked with Jay to confirm this location.

**Comment by jpierel14** [comment]
fixed with daa5bf4597764f36e2289706f036ddd777975c59 (version 0.0.6 on pip)
